//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: template.proto
// Note: requires additional types generated from: symbolic.proto
// Note: requires additional types generated from: openscad.proto
namespace FabByExample.proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TemplateSet")]
  public partial class TemplateSet : global::ProtoBuf.IExtensible
  {
    public TemplateSet() {}
    
    private readonly global::System.Collections.Generic.List<FabByExample.proto.Template> _template = new global::System.Collections.Generic.List<FabByExample.proto.Template>();
    [global::ProtoBuf.ProtoMember(1, Name=@"template", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<FabByExample.proto.Template> template
    {
      get { return _template; }
    }
  
    private int _root_template_id = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"root_template_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int root_template_id
    {
      get { return _root_template_id; }
      set { _root_template_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Template")]
  public partial class Template : global::ProtoBuf.IExtensible
  {
    public Template() {}
    
    private int _id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private readonly global::System.Collections.Generic.List<FabByExample.proto.symbolic.Parameter> _parameter = new global::System.Collections.Generic.List<FabByExample.proto.symbolic.Parameter>();
    [global::ProtoBuf.ProtoMember(3, Name=@"parameter", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<FabByExample.proto.symbolic.Parameter> parameter
    {
      get { return _parameter; }
    }
  
    private FabByExample.proto.MappingFunction _mapping_function = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"mapping_function", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public FabByExample.proto.MappingFunction mapping_function
    {
      get { return _mapping_function; }
      set { _mapping_function = value; }
    }
    private FabByExample.proto.FeasibleSet _feasible_set = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"feasible_set", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public FabByExample.proto.FeasibleSet feasible_set
    {
      get { return _feasible_set; }
      set { _feasible_set = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _child_template_id = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(6, Name=@"child_template_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> child_template_id
    {
      get { return _child_template_id; }
    }
  
    private readonly global::System.Collections.Generic.List<FabByExample.proto.Connection> _connection = new global::System.Collections.Generic.List<FabByExample.proto.Connection>();
    [global::ProtoBuf.ProtoMember(7, Name=@"connection", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<FabByExample.proto.Connection> connection
    {
      get { return _connection; }
    }
  
    private readonly global::System.Collections.Generic.List<FabByExample.proto.Patch> _patch = new global::System.Collections.Generic.List<FabByExample.proto.Patch>();
    [global::ProtoBuf.ProtoMember(8, Name=@"patch", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<FabByExample.proto.Patch> patch
    {
      get { return _patch; }
    }
  
    private bool _independent = default(bool);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"independent", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool independent
    {
      get { return _independent; }
      set { _independent = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Patch")]
  public partial class Patch : global::ProtoBuf.IExtensible
  {
    public Patch() {}
    
    private int _id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private FabByExample.proto.Edge2SPatch _edge2SPatch = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"edge2SPatch", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public FabByExample.proto.Edge2SPatch edge2SPatch
    {
      get { return _edge2SPatch; }
      set { _edge2SPatch = value; }
    }
    private FabByExample.proto.ServoPointPatch _servoPointPatch = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"servoPointPatch", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public FabByExample.proto.ServoPointPatch servoPointPatch
    {
      get { return _servoPointPatch; }
      set { _servoPointPatch = value; }
    }
    private FabByExample.proto.ServoLinePatch _servoLinePatch = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"servoLinePatch", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public FabByExample.proto.ServoLinePatch servoLinePatch
    {
      get { return _servoLinePatch; }
      set { _servoLinePatch = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ServoPointPatch")]
  public partial class ServoPointPatch : global::ProtoBuf.IExtensible
  {
    public ServoPointPatch() {}
    
    private FabByExample.proto.symbolic.Point3S _center = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"center", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public FabByExample.proto.symbolic.Point3S center
    {
      get { return _center; }
      set { _center = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ServoLinePatch")]
  public partial class ServoLinePatch : global::ProtoBuf.IExtensible
  {
    public ServoLinePatch() {}
    
    private FabByExample.proto.symbolic.Point3S _startPoint = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"startPoint", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public FabByExample.proto.symbolic.Point3S startPoint
    {
      get { return _startPoint; }
      set { _startPoint = value; }
    }
    private FabByExample.proto.symbolic.Point3S _endPoint = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"endPoint", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public FabByExample.proto.symbolic.Point3S endPoint
    {
      get { return _endPoint; }
      set { _endPoint = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Edge2SPatch")]
  public partial class Edge2SPatch : global::ProtoBuf.IExtensible
  {
    public Edge2SPatch() {}
    
    private int _edgeId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"edgeId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int edgeId
    {
      get { return _edgeId; }
      set { _edgeId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Connection")]
  public partial class Connection : global::ProtoBuf.IExtensible
  {
    public Connection() {}
    
    private int _parentPatchRef = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"parentPatchRef", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int parentPatchRef
    {
      get { return _parentPatchRef; }
      set { _parentPatchRef = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _patchRef = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"patchRef", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> patchRef
    {
      get { return _patchRef; }
    }
  
    private FabByExample.proto.ConnectionMode _connectionMode = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"connectionMode", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public FabByExample.proto.ConnectionMode connectionMode
    {
      get { return _connectionMode; }
      set { _connectionMode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ConnectionMode")]
  public partial class ConnectionMode : global::ProtoBuf.IExtensible
  {
    public ConnectionMode() {}
    
    private FabByExample.proto.FoldConnection _foldConnection = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"foldConnection", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public FabByExample.proto.FoldConnection foldConnection
    {
      get { return _foldConnection; }
      set { _foldConnection = value; }
    }
    private FabByExample.proto.BendConnection _bendConnection = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"bendConnection", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public FabByExample.proto.BendConnection bendConnection
    {
      get { return _bendConnection; }
      set { _bendConnection = value; }
    }
    private FabByExample.proto.FlexConnection _flexConnection = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"flexConnection", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public FabByExample.proto.FlexConnection flexConnection
    {
      get { return _flexConnection; }
      set { _flexConnection = value; }
    }
    private FabByExample.proto.JointConnection _jointConnection = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"jointConnection", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public FabByExample.proto.JointConnection jointConnection
    {
      get { return _jointConnection; }
      set { _jointConnection = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FoldConnection")]
  public partial class FoldConnection : global::ProtoBuf.IExtensible
  {
    public FoldConnection() {}
    
    private double _angle = default(double);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"angle", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(double))]
    public double angle
    {
      get { return _angle; }
      set { _angle = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"JointConnection")]
  public partial class JointConnection : global::ProtoBuf.IExtensible
  {
    public JointConnection() {}
    
    private double _angle = default(double);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"angle", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(double))]
    public double angle
    {
      get { return _angle; }
      set { _angle = value; }
    }
    private FabByExample.proto.Articulation _articulations = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"articulations", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public FabByExample.proto.Articulation articulations
    {
      get { return _articulations; }
      set { _articulations = value; }
    }
    private FabByExample.proto.PrintType _printType = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"printType", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public FabByExample.proto.PrintType printType
    {
      get { return _printType; }
      set { _printType = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PrintType")]
  public partial class PrintType : global::ProtoBuf.IExtensible
  {
    public PrintType() {}
    
    private bool _ballAndSocket = default(bool);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ballAndSocket", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool ballAndSocket
    {
      get { return _ballAndSocket; }
      set { _ballAndSocket = value; }
    }
    private bool _prismatic = default(bool);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"prismatic", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool prismatic
    {
      get { return _prismatic; }
      set { _prismatic = value; }
    }
    private bool _revolute = default(bool);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"revolute", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool revolute
    {
      get { return _revolute; }
      set { _revolute = value; }
    }
    private bool _none = default(bool);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"none", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool none
    {
      get { return _none; }
      set { _none = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BendConnection")]
  public partial class BendConnection : global::ProtoBuf.IExtensible
  {
    public BendConnection() {}
    
    private double _angle = default(double);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"angle", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(double))]
    public double angle
    {
      get { return _angle; }
      set { _angle = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FlexConnection")]
  public partial class FlexConnection : global::ProtoBuf.IExtensible
  {
    public FlexConnection() {}
    
    private double _angle = default(double);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"angle", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(double))]
    public double angle
    {
      get { return _angle; }
      set { _angle = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MappingFunction")]
  public partial class MappingFunction : global::ProtoBuf.IExtensible
  {
    public MappingFunction() {}
    
    private FabByExample.proto.LinearMappingFunction3 _linear_3 = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"linear_3", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public FabByExample.proto.LinearMappingFunction3 linear_3
    {
      get { return _linear_3; }
      set { _linear_3 = value; }
    }
    private FabByExample.proto.LinearMappingFunction2 _linear_2 = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"linear_2", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public FabByExample.proto.LinearMappingFunction2 linear_2
    {
      get { return _linear_2; }
      set { _linear_2 = value; }
    }
    private FabByExample.proto.CompositionMappingFunction _composition = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"composition", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public FabByExample.proto.CompositionMappingFunction composition
    {
      get { return _composition; }
      set { _composition = value; }
    }
    private FabByExample.proto.ExternalMeshAffineMappingFunction _external_mesh_affine = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"external_mesh_affine", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public FabByExample.proto.ExternalMeshAffineMappingFunction external_mesh_affine
    {
      get { return _external_mesh_affine; }
      set { _external_mesh_affine = value; }
    }
    private FabByExample.proto.ScadMappingFunction _scad = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"scad", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public FabByExample.proto.ScadMappingFunction scad
    {
      get { return _scad; }
      set { _scad = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ScadMappingFunction")]
  public partial class ScadMappingFunction : global::ProtoBuf.IExtensible
  {
    public ScadMappingFunction() {}
    
    private string _scad_filename = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"scad_filename", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string scad_filename
    {
      get { return _scad_filename; }
      set { _scad_filename = value; }
    }
    private FabByExample.proto.OpenscadDesign _design = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"design", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public FabByExample.proto.OpenscadDesign design
    {
      get { return _design; }
      set { _design = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ExternalMeshAffineMappingFunction")]
  public partial class ExternalMeshAffineMappingFunction : global::ProtoBuf.IExtensible
  {
    public ExternalMeshAffineMappingFunction() {}
    
    private string _stl_filename = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"stl_filename", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string stl_filename
    {
      get { return _stl_filename; }
      set { _stl_filename = value; }
    }
    private byte[] _stl_data = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"stl_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] stl_data
    {
      get { return _stl_data; }
      set { _stl_data = value; }
    }
    private FabByExample.proto.symbolic.AffineMatrix3S _transform = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"transform", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public FabByExample.proto.symbolic.AffineMatrix3S transform
    {
      get { return _transform; }
      set { _transform = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CompositionMappingFunction")]
  public partial class CompositionMappingFunction : global::ProtoBuf.IExtensible
  {
    public CompositionMappingFunction() {}
    
    private readonly global::System.Collections.Generic.List<int> _template_id = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(1, Name=@"template_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> template_id
    {
      get { return _template_id; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LinearMappingFunction3")]
  public partial class LinearMappingFunction3 : global::ProtoBuf.IExtensible
  {
    public LinearMappingFunction3() {}
    
    private FabByExample.proto.symbolic.Mesh3S _mesh = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"mesh", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public FabByExample.proto.symbolic.Mesh3S mesh
    {
      get { return _mesh; }
      set { _mesh = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LinearMappingFunction2")]
  public partial class LinearMappingFunction2 : global::ProtoBuf.IExtensible
  {
    public LinearMappingFunction2() {}
    
    private FabByExample.proto.symbolic.Drawing2S _drawing = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"drawing", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public FabByExample.proto.symbolic.Drawing2S drawing
    {
      get { return _drawing; }
      set { _drawing = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FeasibleSet")]
  public partial class FeasibleSet : global::ProtoBuf.IExtensible
  {
    public FeasibleSet() {}
    
    private FabByExample.proto.ConstraintList _constraint_list = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"constraint_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public FabByExample.proto.ConstraintList constraint_list
    {
      get { return _constraint_list; }
      set { _constraint_list = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ConstraintList")]
  public partial class ConstraintList : global::ProtoBuf.IExtensible
  {
    public ConstraintList() {}
    
    private readonly global::System.Collections.Generic.List<FabByExample.proto.Constraint> _constraint = new global::System.Collections.Generic.List<FabByExample.proto.Constraint>();
    [global::ProtoBuf.ProtoMember(1, Name=@"constraint", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<FabByExample.proto.Constraint> constraint
    {
      get { return _constraint; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _inherited_template_id = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"inherited_template_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> inherited_template_id
    {
      get { return _inherited_template_id; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Constraint")]
  public partial class Constraint : global::ProtoBuf.IExtensible
  {
    public Constraint() {}
    
    private FabByExample.proto.LinearConstraint _linear_constraint = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"linear_constraint", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public FabByExample.proto.LinearConstraint linear_constraint
    {
      get { return _linear_constraint; }
      set { _linear_constraint = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LinearConstraint")]
  public partial class LinearConstraint : global::ProtoBuf.IExtensible
  {
    public LinearConstraint() {}
    
    private FabByExample.proto.symbolic.LinearExpr _expr = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"expr", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public FabByExample.proto.symbolic.LinearExpr expr
    {
      get { return _expr; }
      set { _expr = value; }
    }
    private FabByExample.proto.LinearConstraint.Type _type = FabByExample.proto.LinearConstraint.Type.EQUALITY;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(FabByExample.proto.LinearConstraint.Type.EQUALITY)]
    public FabByExample.proto.LinearConstraint.Type type
    {
      get { return _type; }
      set { _type = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"Type")]
    public enum Type
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"EQUALITY", Value=1)]
      EQUALITY = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LESS_THAN_ZERO", Value=2)]
      LESS_THAN_ZERO = 2
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Articulation")]
  public partial class Articulation : global::ProtoBuf.IExtensible
  {
    public Articulation() {}
    
    private readonly global::System.Collections.Generic.List<FabByExample.proto.symbolic.Transform> _transforms = new global::System.Collections.Generic.List<FabByExample.proto.symbolic.Transform>();
    [global::ProtoBuf.ProtoMember(1, Name=@"transforms", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<FabByExample.proto.symbolic.Transform> transforms
    {
      get { return _transforms; }
    }
  
    private FabByExample.proto.symbolic.Point3S _center = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"center", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public FabByExample.proto.symbolic.Point3S center
    {
      get { return _center; }
      set { _center = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}